#!/usr/bin/env perl

use strict;
use warnings;
use FindBin qw($Bin);
use File::Spec;

my $unicode_version = '13.0.0';
my $data_dir = shift // File::Spec->catdir(
    $Bin, '..', 'tests', 'unicode', $unicode_version);

my %class_name = map { $_ => "BIDI_$_" } qw(
    L R AL EN ES ET AN CS NSM BN B S WS ON
    LRE RLE LRO RLO PDF LRI RLI FSI PDI
);

sub data_lines {
    my ($filename) = @_;
    my $path = File::Spec->catfile($data_dir, $filename);
    open my $file, '<', $path or die "Cannot open $path: $!\n";
    my $header = <$file> // die "$path is empty\n";
    die "$path is not Unicode $unicode_version data\n"
        unless $header =~ /-\Q$unicode_version\E\.txt/;
    my @lines;
    while (my $line = <$file>) {
        $line =~ s/#.*//;
        $line =~ s/^\s+|\s+$//g;
        push @lines, $line if length $line;
    }
    close $file or die "Cannot close $path: $!\n";
    return @lines;
}

my @ranges;
for my $line (data_lines('DerivedBidiClass.txt')) {
    next unless $line =~ /^([0-9A-F]+)(?:\.\.([0-9A-F]+))?\s*;\s*(\w+)$/;
    my ($lo, $hi, $class) = (hex($1), hex($2 // $1), $3);
    die "Unknown Bidi_Class '$class'\n" unless exists $class_name{$class};
    push @ranges, [$lo, $hi, $class] unless $class eq 'L';
}
@ranges = sort { $a->[0] <=> $b->[0] } @ranges;
my @merged;
for my $range (@ranges) {
    if (@merged && $merged[-1][1] + 1 == $range->[0] &&
        $merged[-1][2] eq $range->[2]) {
        $merged[-1][1] = $range->[1];
    } else {
        push @merged, [@$range];
    }
}

my @brackets;
for my $line (data_lines('BidiBrackets.txt')) {
    die "Malformed BidiBrackets line: $line\n"
        unless $line =~ /^([0-9A-F]+)\s*;\s*([0-9A-F]+)\s*;\s*([oc])$/;
    push @brackets, [hex($1), hex($2), $3];
}

my @mirrors;
for my $line (data_lines('BidiMirroring.txt')) {
    die "Malformed BidiMirroring line: $line\n"
        unless $line =~ /^([0-9A-F]+)\s*;\s*([0-9A-F]+)$/;
    push @mirrors, [hex($1), hex($2)];
}

print <<"HEADER";
/* Generated by tools/generate_bidi_data.pl from Unicode $unicode_version. */
#ifndef SIMPLE_TERMSHOT_BIDI_DATA_H
#define SIMPLE_TERMSHOT_BIDI_DATA_H

#define BIDI_UNICODE_VERSION "$unicode_version"

struct bidi_range {
    uint32_t lo;
    uint32_t hi;
    bidi_type_t type;
};

static const struct bidi_range bidi_ranges[] = {
HEADER

for my $range (@merged) {
    printf "    {0x%06X, 0x%06X, %s},\n",
        $range->[0], $range->[1], $class_name{$range->[2]};
}

print <<'MIDDLE';
};

#define BIDI_RANGES_COUNT \
    ((int)(sizeof(bidi_ranges) / sizeof(bidi_ranges[0])))

struct bidi_bracket_entry {
    uint32_t codepoint;
    uint32_t pair;
    bidi_bracket_type_t kind;
};

static const struct bidi_bracket_entry bidi_brackets[] = {
MIDDLE

for my $entry (@brackets) {
    my $kind = $entry->[2] eq 'o' ? 'BIDI_BRACKET_OPEN' : 'BIDI_BRACKET_CLOSE';
    printf "    {0x%06X, 0x%06X, %s},\n", $entry->[0], $entry->[1], $kind;
}

print <<'MIRRORS';
};

#define BIDI_BRACKETS_COUNT \
    ((int)(sizeof(bidi_brackets) / sizeof(bidi_brackets[0])))

struct bidi_mirror_entry {
    uint32_t codepoint;
    uint32_t mirror;
};

static const struct bidi_mirror_entry bidi_mirrors[] = {
MIRRORS

for my $entry (@mirrors) {
    printf "    {0x%06X, 0x%06X},\n", $entry->[0], $entry->[1];
}

print <<'FOOTER';
};

#define BIDI_MIRRORS_COUNT \
    ((int)(sizeof(bidi_mirrors) / sizeof(bidi_mirrors[0])))

#endif /* SIMPLE_TERMSHOT_BIDI_DATA_H */
FOOTER
